server:
  port: 80

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
spring:
  datasource:
    url: jdbc:p6spy:mysql://39.108.248.78:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  redis:
    database: 0
    host: 39.108.248.78
    port: 6379






